#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-reflectasm
Version  : 1.07
Release  : 1
URL      : https://github.com/EsotericSoftware/reflectasm/archive/1.07.tar.gz
Source0  : https://github.com/EsotericSoftware/reflectasm/archive/1.07.tar.gz
Source1  : https://repo1.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07.jar
Source2  : https://repo1.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-reflectasm-data = %{version}-%{release}
Requires: mvn-reflectasm-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-reflectasm package.
Group: Data

%description data
data components for the mvn-reflectasm package.


%package license
Summary: license components for the mvn-reflectasm package.
Group: Default

%description license
license components for the mvn-reflectasm package.


%prep
%setup -q -n reflectasm-1.07

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-reflectasm
cp license.txt %{buildroot}/usr/share/package-licenses/mvn-reflectasm/license.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07.jar
/usr/share/java/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-reflectasm/license.txt
